#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EMMAUI_DIR="${1:-$ROOT_DIR/../emmaui}"
IOS_FRAMEWORK_DIR="${2:-$ROOT_DIR/artifacts/ios-native-framework}"
RUN_POD_INSTALL="${RUN_POD_INSTALL:-1}"

IOS_DIR="$EMMAUI_DIR/ios"
POD_NAME="EMMANativeRuntime"
POD_DIR="$IOS_DIR/$POD_NAME"
PODSPEC_PATH="$POD_DIR/$POD_NAME.podspec"
PODFILE_PATH="$IOS_DIR/Podfile"

NATIVE_XCFRAMEWORK_SRC="$IOS_FRAMEWORK_DIR/EmmaNative.xcframework"
WASM_XCFRAMEWORK_SRC="$IOS_FRAMEWORK_DIR/EmmaWasmRuntime.xcframework"

if [[ ! -d "$IOS_DIR" ]]; then
  echo "emmaui iOS directory does not exist: $IOS_DIR"
  exit 1
fi

if [[ ! -d "$NATIVE_XCFRAMEWORK_SRC" ]]; then
  echo "Missing XCFramework: $NATIVE_XCFRAMEWORK_SRC"
  echo "Run ./scripts/build-ios-native-framework.sh first."
  exit 1
fi

if [[ ! -d "$WASM_XCFRAMEWORK_SRC" ]]; then
  echo "Missing XCFramework: $WASM_XCFRAMEWORK_SRC"
  echo "Run ./scripts/build-ios-native-framework.sh first."
  exit 1
fi

echo "[1/4] Syncing XCFrameworks into emmaui iOS local pod..."
rm -rf "$POD_DIR"
mkdir -p "$POD_DIR/Frameworks"

cp -R "$NATIVE_XCFRAMEWORK_SRC" "$POD_DIR/Frameworks/EmmaNative.xcframework"
cp -R "$WASM_XCFRAMEWORK_SRC" "$POD_DIR/Frameworks/EmmaWasmRuntime.xcframework"

echo "[2/4] Writing local podspec..."
cat > "$PODSPEC_PATH" <<'EOF'
Pod::Spec.new do |s|
  s.name             = 'EMMANativeRuntime'
  s.version          = '1.0.0'
  s.summary          = 'EMMA iOS native runtime (static XCFrameworks)'
  s.description      = 'Statically linked EMMA native runtime and WASM runtime for iOS.'
  s.homepage         = 'https://example.local/emma'
  s.license          = { :type => 'Proprietary' }
  s.author           = { 'EMMA' => 'team@emma.local' }
  s.source           = { :path => '.' }
  s.platform         = :ios, '13.0'
  s.vendored_frameworks = [
    'Frameworks/EmmaNative.xcframework',
    'Frameworks/EmmaWasmRuntime.xcframework'
  ]
  s.user_target_xcconfig = {
    'OTHER_LDFLAGS' => '$(inherited) -Wl,-u,_emma_wasm_component_invoke -Wl,-u,_emma_wasm_runtime_free_string'
  }
end
EOF

cat > "$POD_DIR/README.md" <<'EOF'
# EMMANativeRuntime

Generated by EMMA/scripts/sync-ios-native-framework-to-emmaui.sh.

Contains prebuilt static XCFrameworks:

- EmmaNative.xcframework
- EmmaWasmRuntime.xcframework

Do not edit manually.
EOF

echo "[3/4] Ensuring Podfile references $POD_NAME..."
if ! grep -q "pod '$POD_NAME'" "$PODFILE_PATH"; then
  python3 - "$PODFILE_PATH" "$POD_NAME" <<'PY'
import sys
from pathlib import Path

podfile_path = Path(sys.argv[1])
pod_name = sys.argv[2]
text = podfile_path.read_text()
needle = "flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))"
insert = f"  pod '{pod_name}', :path => './{pod_name}'\n\n  {needle}"

if needle not in text:
    raise SystemExit(f"Could not find insertion point in {podfile_path}")

if f"pod '{pod_name}'" not in text:
    text = text.replace(needle, insert, 1)
    podfile_path.write_text(text)
PY
fi

echo "[4/4] Running pod install (optional)..."
if [[ "$RUN_POD_INSTALL" == "1" ]]; then
  (
    cd "$IOS_DIR"
    pod install
  )
else
  echo "Skipped pod install because RUN_POD_INSTALL=$RUN_POD_INSTALL"
fi

echo "iOS native runtime sync complete."
echo "  pod dir: $POD_DIR"
echo "  podspec: $PODSPEC_PATH"
